### ISSUE TITLE
Support for dalamud api 7

### ISSUE THREAD

**Issue by Battler624** [ArchiDog1998/XIVAutoAttack#14]
Any chance for this to support dalamud api 7 and game version 6.28?

**Comment by ArchiDog1998** [comment]
Hi Battler,

This plugin will be updated to dalamud `api 7` in one week, but for game version `6.18` in Chinese server. I don't have any account to access any other server to test this plugin for version 6.28 in FFXIV. I'm sorry for that.

**Comment by ArchiDog1998** [comment]
Hi,
I think I got some misinformation. The game version `6.18` doesn't patch the dalamud `API 7` but `API 6`. After the game has been updated to version `6.20`, `API 7` will be supported.
